version: "3.17"

services:
  storage-table:
    build:
      context: ./back-end/StorageTable
    ports:
      - "10002:10002"
    networks:
      - customer-network
    volumes:
      - table-storage-volume:/storage

  customer-api:
    build:
      context: ./back-end/CustomerAPI/CustomerAPI
    ports:
      - "8080:80"
    networks:
      - customer-network
    secrets:
      - source: table-storage-secret
        target: /app/secrets.json

  prometheus:
    build:
      context: monitoring/Prometheus
    volumes:
      - type: bind
        source: ./monitoring/Prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true
    ports:
      - "9090:9090"
    networks:
      - customer-network

  grafana:
    build:
      context: monitoring/Grafana
    ports:
      - "3000:3000"
    networks:
      - customer-network

secrets:
  table-storage-secret:
    file: ./secrets-dev-only/secrets.json

volumes:
  table-storage-volume:

networks:
  customer-network:
    name: customer-net
