version: "3.17"

services:
  storage-table:
    image: palopodstreleny/storage-table-emulator:latest

  customer-api:
    image: palopodstreleny/customer-api:latest

  prometheus:
    image: palopodstreleny/prometheus:latest

  grafana:
    image: palopodstreleny/grafana:latest
