version: "3.7"

x-args: &args
  args:
    BUILD_NUMBER: ${BUILD_NUMBER:-0}
    BUILD_TAG: ${BUILD_TAG:-local}

services:
  kibana:
    build:
      context: ./Kibana/
      <<: *args
  elasticsearch:
    build:
      context: ./ElasticSearch/
      <<: *args
  fluentd:
    build:
      context: ./Fluentd/
      <<: *args
