version: "3.7"

x-args: &args
  args:
    BUILD_NUMBER: ${BUILD_NUMBER:-0}
    BUILD_TAG: ${BUILD_TAG:-local}

services:
  grafana:
    build:
      context: ./Grafana/
      <<: *args
  prometheus:
    build:
      context: ./Prometheus/
      <<: *args
