version: "3.17"

services:
  prometheus:
    volumes:
      - type: bind
        source: ./Prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true
    ports:
      - "9090:9090"
    networks:
      - customer-network

  grafana:
    ports:
      - "3000:3000"
    networks:
      - customer-network

networks:
  customer-network:
    name: customer-network-monitor-dev
