name: Customer-App-Backend-$(Date:yyyyMMdd)
trigger:
  - backend

variables:
  - name: customerApiTestImageName
    value: palopodstreleny/customer-api-test:latest
    readonly: true
  - name: customerApiImageName
    value: palopodstreleny/customer-api:latest
    readonly: true

pool:
  name: CoustomerProject

stages:
  - stage: Testing_Customer_API
    displayName: Testing Customer API
    jobs:
      - job: "Build_Container_Test"
        displayName: Build Customer API Test Container
        steps:
          - bash: docker image build -t ${{variables.customerApiTestImageName}} .
            workingDirectory: back-end/CustomerAPI/CustomerAPI.Test

      - job: "Run_Container_Test"
        displayName: Runs Customer API Test Container
        steps:
          - bash: docker container run ${{variables.customerApiTestImageName}}
          - bash: docker container logs ${{variables.customerApiTestImageName}}
        dependsOn: "Build_Container_Test"

      - job: "Build_Container"
        displayName: Build Customer API Container
        steps:
          - bash: docker image build -t ${{variables.customerApiImageName}}
            workingDirectory: back-end/CustomerAPI/CustomerAPI.Test
        dependsOn: "Run_Container_Test"
