name: Customer-App-Backend-$(Date:yyyyMMdd)
trigger:
  - backend

variables:
  - name: customerApiImageName
    value: palopodstrleleny/customer-api:latest

stages:
  - stage: Testing Customer API
    displayName: Testing Customer API
    jobs:
      - job: "Build-Container"
        displayName: Build Customer API container
        steps:
          - bash: docker container build -t "${{ variables.customerApiImageName}}"
      - job: "Test-Container"
        displayName: Testing Customer API inside container
        steps:
          - bash: docker container run ${{ variables.customerApiImageName}}
