name: Backend-Build-$(Build.BuildId)-$(Date:yyyyMMdd)
trigger:
  - backend
  - cicd

variables:
  - group: customer-app
  - name: backendCI
    value: back-end/ci/
    readonly: true
  - name: ci
    value: ci/
    readonly: true

pool:
  name: CoustomerProject

stages:
  - stage: Verify
    displayName: Verify Docker and Docker-Compose dependencies
    jobs:
      - job:
        displayName: Verify docker and docker-compose
        steps:
          - bash: sh verify.sh
            workingDirectory: ${{variables.ci}}

  - stage: Build
    displayName: Build Containers For Backend
    jobs:
      - job:
        timeoutInMinutes: 8
        displayName: Build Containers
        steps:
          - bash: sh build.sh
            workingDirectory: ${{variables.backendCI}}

  - stage: Test
    displayName: Test Containers For Backend
    jobs:
      - job:
        timeoutInMinutes: 8
        displayName: Test Containers
        steps:
          - bash: sh test.sh
            workingDirectory: ${{variables.backendCI}}
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: "xUnit"
              testResultsFiles: "**/TestResults/**/*.xml"
              failTaskOnFailedTests: true
    dependsOn: Build

  - stage: Push
    displayName: Publish Containers To DockerHub
    jobs:
      - job:
        timeoutInMinutes: 8
        displayName: Publish Containers
        steps:
          - bash: sh login.sh
            env:
              DOCKER_LOGIN: $(Docker.login)
              DOCKER_CREDENTIALS: $(Docker.credentials)
            workingDirectory: ${{variables.ci}}
          - bash: sh publish.sh
            workingDirectory: ${{variables.backendCI}}
    dependsOn: Test
