name: Customer-App-Backend-$(Date:yyyyMMdd)
trigger:
  - backend

variables:
  - name: customerApiImageName
    value: palopodstreleny/customer-api:latest
    readonly: true

pool:
  name: CoustomerProject

stages:
  - stage: Testing_Customer_API
    displayName: Testing Customer API
    jobs:
      - job: "Build_Container"
        displayName: Build Customer API container
        steps:
          - bash: docker image build -t "${{ variables.customerApiImageName}}" .
      - job: "Test_Container"
        displayName: Testing Customer API inside container
        steps:
          - bash: docker container run ${{ variables.customerApiImageName}}
