version: "3.7"

services:
  storage-table:
    image: ${DOCKER_REGISTRY:-docker.io}/palopodstreleny/storage-table-emulator:v1-build-${BUILD_NUMBER:-local}
  customer-api:
    image: ${DOCKER_REGISTRY:-docker.io}/palopodstreleny/customer-api:v1-build-${BUILD_NUMBER:-local}
  customer-api-test:
    image: ${DOCKER_REGISTRY:-docker.io}/palopodstreleny/customer-api-test:v1-build-${BUILD_NUMBER:-local}
